import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { ClerkProvider } from '@clerk/nextjs';

import { Toaster } from '@/components/ui/sonner';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin']
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin']
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <ClerkProvider
                appearance={{
                    layout: {
                        logoImageUrl: '/icons/yoom-logo.svg',
                        socialButtonsVariant: 'iconButton'
                    },
                    variables: {
                        colorText: '#fff',
                        colorPrimary: '#0E78F9',
                        colorBackground: '#1c1f2e',
                        colorInputBackground: '#252a41',
                        colorInputText: '#fff'
                    }
                }}
            >
                <body
                    className={`${geistSans.variable} ${geistMono.variable} antialiased bg-dark`}
                >
                    {children}
                    <Toaster
                        toastOptions={{
                            className: 'bg-dark text-white',
                            duration: 3000,
                            style: {
                                backgroundColor: '#1c1f2e',
                                color: '#fff'
                            }
                        }}
                        closeButton={false}
                    />
                </body>
            </ClerkProvider>
        </html>
    );
}
